Feature: teleport player to nearest lobby if they fall in the void.
A5H73Y/Parkour pull request #250
Opened 2020-12-29 23:28 UTC by FrankHeijden

2020-12-29 23:31 UTC, A5H73Y requested changes

2020-12-29 23:31 UTC, A5H73Y commented on src/main/java/io/github/a5h73y/parkour/listener/PlayerMoveListener.java
> +                if (player.getLocation().getY() < 0) {
Rather than run this on every move event, I would rather you moved it to the Void damage detection method.

2020-12-30 01:09 UTC, thiccaxe commented
probably want to tp to last lobby instead of nearest.

2020-12-30 12:06 UTC, A5H73Y approved these changes

2020-12-30 12:06 UTC, merged