add events for parkour reset commands
A5H73Y/Parkour pull request #322
Opened 2022-05-19 07:58 UTC by steve4744

2022-05-19 08:04 UTC, steve4744 commented
Add a Parkour event for resetting a player, course and leader board.

2022-05-19 16:01 UTC, A5H73Y requested changes

2022-05-20 08:33 UTC, steve4744 commented on src/main/java/io/github/a5h73y/parkour/type/player/PlayerManager.java
> +		Bukkit.getServer().getPluginManager().callEvent(new ParkourResetPlayerEvent((Player)targetPlayer, null));
That's fine, and is now updated.

2022-05-20 08:33 UTC, steve4744 commented on src/main/java/io/github/a5h73y/parkour/type/course/CourseManager.java
> +        Bukkit.getServer().getPluginManager().callEvent(new ParkourResetLeaderboardEvent((Player) targetPlayer, courseName));
...and here.

2022-05-20 09:04 UTC, A5H73Y approved these changes

2022-05-20 09:04 UTC, merged