Save allow flight as snapshot data & run commands with a delay
A5H73Y/Parkour pull request #349
Opened 2023-09-06 18:55 UTC by BlendyDev

2023-09-13 20:28 UTC, A5H73Y requested changes

2023-09-15 20:03 UTC, BlendyDev commented on src/main/java/io/github/a5h73y/parkour/type/player/PlayerManager.java
> +				rewardPrize(player, session);
I dont think I tested without that change. I just wanted commands like /item working

2023-09-15 20:05 UTC, BlendyDev commented on src/main/java/io/github/a5h73y/parkour/type/course/CourseManager.java
> +        }.runTaskLater(parkour, 2L);
Want me to impl that? Im on GH mobile so idk if you suggested changes or anything

2025-01-04 09:34 UTC, A5H73Y commented
Recreated clean version locally.

2025-01-04 09:34 UTC, closed without merging